### ISSUE TITLE
Is it possible to tag this repo ?

### ISSUE THREAD

**Issue by itkg-ngilain** [f1nder/SolutionMongoAggregationBundle#5]
Hi,

we are using the f1nder/SolutionMongoAggregationBundle on our project (https://github.com/open-orchestra/open-orchestra). It perfectly meets our needs, but now we are rewriting our composer.json with a minimum-stability:stable and we are encountering some issues with it. As it doesn't have any tag, we need to whitelist it with @dev on each bundles requiring a bundle using SolutionMongoAggregationBundle. It would be far more simple if we could rely on a stable tag instead of the dev-master branch.

So here is my question: could you create a tag, even a 0.1 would be sufficient for us as long as it is recognized as a stable version by packagist.

Thank you for your work :)

**Comment by itkg-ngilain** [comment]
I forgot to talk about f1nder/SolutionPipelineBuilder. We have the same issue with this dependency, so it would great if you could tag it too :)

Thank you !

**Comment by f1nder** [comment]
Hi, 
I created tag v0.1 for bundle and library.
p.s. great CMS..

**Comment by itkg-ngilain** [comment]
Thank you very much for these tags :)

**Comment by itkg-ngilain** [comment]
I'm sorry to bother you again, but there is a little problem with the tag v0.1. In the composer.json, the dependency to "solution/pipeline-builder" is set to "dev-master". Could you alter it or recreate a new tag to require the stable version of "solution/pipeline-builder" ?

Thank you

**Comment by f1nder** [comment]
done https://github.com/f1nder/SolutionMongoAggregationBundle/tree/v0.1.1

**Comment by ngilain** [comment]
Than you for this,

we have upgraded our composer.json with it
